spring:
  application:
    name: usercenter
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      ack:
        enabled: true
      trace:
        enabled: true
---
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh