spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/approvelove/SpringCloudConfigCenter/
          search-paths: yml
          username: approvelove
          password: huilanwoaini0
      label: master
---
server:
  port: 8888

---
eureka:
  client:
    service-url:
      default-zone: http://localhost:8889/eureka/