spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/approvelove/SpringCloudConfig/
          search-paths: config-center
          username: approvelove
          password: huilanwoaini0
      label: master
---
server:
  port: 8888